name: example_workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Application Build
        run: npm install && npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2 
        with:
          name: react_test_app
          path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: react_test_app
      - name: Deploy on Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'santisl5_test_react_app.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_password }}
