name: main_workflow
on:
  push:
    branches:
      - nodejs_linter_job
      - nodejs_jest_job
      - nodejs_nodeversions_job
      - nodejs_environment_job
jobs:
  linter-execution:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/nodejs_jest_job'
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Linter execution
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: nodejs_example
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        LINTER_RULES_PATH: /
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
        VALIDATE_JAVASCRIPT_ES: true
  test-execution:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node: [ '10', '12' ]
   name: Node ${{ matrix.node }}
   if: github.ref == 'refs/heads/nodejs_environment_job'
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Setup node
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node }}
     - name: Run jest tests
       run: npm install jest && npm test
  environment_test_execution:
   runs-on: ubuntu-latest
   env:
      DESTINATION_PERSON: 2DAW
   steps:
     - name: Hello 2DAW
       uses: actions/github-actions-hello@v1
       with:
         who-to-greet: 'Hello $DESTINATION_PERSON'
